<?php

/*
 * This file is part of the twelvepics-com/php-location-api project.
 *
 * (c) Björn Hempel <https://www.hempel.li/>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace App\Constants\Property\Airport;

/**
 * Class IataIgnore
 *
 * @author Björn Hempel <bjoern@hempel.li>
 * @version 0.1.0 (2024-02-28 00:34:20)
 * @since 0.1.0 (2024-02-28 00:34:20) Automatically generated by IgnoreBuilder class.
 */
class IataIgnore
{
    final public const IGNORE = [
        'BFE' => [
            'key' => 'BFE',
            'reason' => 'No page available.',
        ],
        'EIB' => [
            'key' => 'EIB',
            'reason' => 'No page available.',
        ],
        'GKE' => [
            'key' => 'GKE',
            'reason' => 'No page available.',
        ],
        'GUT' => [
            'key' => 'GUT',
            'reason' => 'No page available.',
        ],
        'IZE' => [
            'key' => 'IZE',
            'reason' => 'No page available.',
        ],
        'OBF' => [
            'key' => 'OBF',
            'reason' => 'No page available.',
        ],
        'QPK' => [
            'key' => 'QPK',
            'reason' => 'No page available.',
        ],
        'SPM' => [
            'key' => 'SPM',
            'reason' => 'No page available.',
        ],
        'WBG' => [
            'key' => 'WBG',
            'reason' => 'No page available.',
        ],
        'WIE' => [
            'key' => 'WIE',
            'reason' => 'No page available.',
        ],
        'ZCN' => [
            'key' => 'ZCN',
            'reason' => 'No page available.',
        ],
        'ZMG' => [
            'key' => 'ZMG',
            'reason' => 'No page available.',
        ],
    ];
}