parameters:
    feature_class_a: 'A'
    feature_class_h: 'H'
    feature_class_l: 'L'
    feature_class_p: 'P'
    feature_class_r: 'R'
    feature_class_s: 'S'
    feature_class_t: 'T'
    feature_class_u: 'U'
    feature_class_v: 'V'

    feature_classes_all:
        - '%feature_class_a%'
        - '%feature_class_h%'
        - '%feature_class_l%'
        - '%feature_class_p%'
        - '%feature_class_r%'
        - '%feature_class_s%'
        - '%feature_class_t%'
        - '%feature_class_u%'
        - '%feature_class_v%'

    feature_class_a_description: 'country, state, region, ...'
    feature_class_h_description: 'stream, lake, ...'
    feature_class_l_description: 'parks, area, ...'
    feature_class_p_description: 'city, village, ...'
    feature_class_r_description: 'road, railroad, ...'
    feature_class_s_description: 'spot, building, farm, ...'
    feature_class_t_description: 'mountain, hill, rock, ...'
    feature_class_u_description: 'undersea'
    feature_class_v_description: 'forest, heath, ...'
