parameters:
    feature_codes_a_all:
        - 'ADM1'
        - 'ADM1H'
        - 'ADM2'
        - 'ADM2H'
        - 'ADM3'
        - 'ADM3H'
        - 'ADM4'
        - 'ADM4H'
        - 'ADM5'
        - 'ADM5H'
        - 'ADMD'
        - 'ADMDH'
        - 'LTER'
        - 'PCL'
        - 'PCLD'
        - 'PCLF'
        - 'PCLH'
        - 'PCLI'
        - 'PCLIX'
        - 'PCLS'
        - 'PRSH'
        - 'TERR'
        - 'ZN'
        - 'ZNB'
    feature_codes_h_all:
        - 'AIRS'
        - 'ANCH'
        - 'BAY'
        - 'BAYS'
        - 'BGHT'
        - 'BNK'
        - 'BNKR'
        - 'BNKX'
        - 'BOG'
        - 'CAPG'
        - 'CHN'
        - 'CHNL'
        - 'CHNM'
        - 'CHNN'
        - 'CNFL'
        - 'CNL'
        - 'CNLA'
        - 'CNLB'
        - 'CNLD'
        - 'CNLI'
        - 'CNLN'
        - 'CNLQ'
        - 'CNLSB'
        - 'CNLX'
        - 'COVE'
        - 'CRKT'
        - 'CRNT'
        - 'CUTF'
        - 'DCK'
        - 'DCKB'
        - 'DOMG'
        - 'DPRG'
        - 'DTCH'
        - 'DTCHD'
        - 'DTCHI'
        - 'DTCHM'
        - 'ESTY'
        - 'FISH'
        - 'FJD'
        - 'FJDS'
        - 'FLLS'
        - 'FLLSX'
        - 'FLTM'
        - 'FLTT'
        - 'GLCR'
        - 'GULF'
        - 'GYSR'
        - 'HBR'
        - 'HBRX'
        - 'INLT'
        - 'INLTQ'
        - 'LBED'
        - 'LGN'
        - 'LGNS'
        - 'LGNX'
        - 'LK'
        - 'LKC'
        - 'LKI'
        - 'LKN'
        - 'LKNI'
        - 'LKO'
        - 'LKOI'
        - 'LKS'
        - 'LKSB'
        - 'LKSC'
        - 'LKSI'
        - 'LKSN'
        - 'LKSNI'
        - 'LKX'
        - 'MFGN'
        - 'MGV'
        - 'MOOR'
        - 'MRSH'
        - 'MRSHN'
        - 'NRWS'
        - 'OCN'
        - 'OVF'
        - 'PND'
        - 'PNDI'
        - 'PNDN'
        - 'PNDNI'
        - 'PNDS'
        - 'PNDSF'
        - 'PNDSI'
        - 'PNDSN'
        - 'POOL'
        - 'POOLI'
        - 'RCH'
        - 'RDGG'
        - 'RDST'
        - 'RF'
        - 'RFC'
        - 'RFX'
        - 'RPDS'
        - 'RSV'
        - 'RSVI'
        - 'RSVT'
        - 'RVN'
        - 'SBKH'
        - 'SD'
        - 'SEA'
        - 'SHOL'
        - 'SILL'
        - 'SPNG'
        - 'SPNS'
        - 'SPNT'
        - 'STM'
        - 'STMA'
        - 'STMB'
        - 'STMC'
        - 'STMD'
        - 'STMH'
        - 'STMI'
        - 'STMIX'
        - 'STMM'
        - 'STMQ'
        - 'STMS'
        - 'STMSB'
        - 'STMX'
        - 'STRT'
        - 'SWMP'
        - 'SYSI'
        - 'TNLC'
        - 'WAD'
        - 'WADB'
        - 'WADJ'
        - 'WADM'
        - 'WADS'
        - 'WADX'
        - 'WHRL'
        - 'WLL'
        - 'WLLQ'
        - 'WLLS'
        - 'WTLD'
        - 'WTLDI'
        - 'WTRC'
        - 'WTRH'
    feature_codes_l_all:
        - 'AGRC'
        - 'AMUS'
        - 'AREA'
        - 'BSND'
        - 'BSNP'
        - 'BTL'
        - 'CLG'
        - 'CMN'
        - 'CNS'
        - 'COLF'
        - 'CONT'
        - 'CST'
        - 'CTRB'
        - 'DEVH'
        - 'FLD'
        - 'FLDI'
        - 'GASF'
        - 'GRAZ'
        - 'GVL'
        - 'INDS'
        - 'LAND'
        - 'LCTY'
        - 'MILB'
        - 'MNA'
        - 'MVA'
        - 'NVB'
        - 'OAS'
        - 'OILF'
        - 'PEAT'
        - 'PRK'
        - 'PRT'
        - 'QCKS'
        - 'RES'
        - 'RESA'
        - 'RESF'
        - 'RESH'
        - 'RESN'
        - 'RESP'
        - 'RESV'
        - 'RESW'
        - 'RGN'
        - 'RGNE'
        - 'RGNH'
        - 'RGNL'
        - 'RNGA'
        - 'SALT'
        - 'SNOW'
        - 'TRB'
    feature_codes_p_all:
        - 'PPL'
        - 'PPLA'
        - 'PPLA2'
        - 'PPLA3'
        - 'PPLA4'
        - 'PPLA5'
        - 'PPLC'
        - 'PPLF'
        - 'PPLG'
        - 'PPLQ'
        - 'PPLR'
        - 'PPLS'
        - 'PPLW'
        - 'PPLX'
        - 'STLMT'
    feature_codes_r_all:
        - 'CSWY'
        - 'OILP'
        - 'PRMN'
        - 'PTGE'
        - 'RD'
        - 'RDA'
        - 'RDB'
        - 'RDCUT'
        - 'RDJCT'
        - 'RJCT'
        - 'RR'
        - 'RRQ'
        - 'RTE'
        - 'RYD'
        - 'ST'
        - 'STKR'
        - 'TNL'
        - 'TNLN'
        - 'TNLRD'
        - 'TNLRR'
        - 'TNLS'
        - 'TRL'
    feature_codes_s_all:
        - 'ADMF'
        - 'AGRF'
        - 'AIRB'
        - 'AIRF'
        - 'AIRH'
        - 'AIRP'
        - 'AIRQ'
        - 'AIRT'
        - 'AMTH'
        - 'ANS'
        - 'AQC'
        - 'ARCH'
        - 'ARCHV'
        - 'ART'
        - 'ASTR'
        - 'ASYL'
        - 'ATHF'
        - 'ATM'
        - 'BANK'
        - 'BCN'
        - 'BDG'
        - 'BDGQ'
        - 'BLDA'
        - 'BLDG'
        - 'BLDO'
        - 'BP'
        - 'BRKS'
        - 'BRKW'
        - 'BSTN'
        - 'BTYD'
        - 'BUR'
        - 'BUSTN'
        - 'BUSTP'
        - 'CARN'
        - 'CAVE'
        - 'CH'
        - 'CMP'
        - 'CMPL'
        - 'CMPLA'
        - 'CMPMN'
        - 'CMPO'
        - 'CMPQ'
        - 'CMPRF'
        - 'CMTY'
        - 'COMC'
        - 'CRRL'
        - 'CSNO'
        - 'CSTL'
        - 'CSTM'
        - 'CTHSE'
        - 'CTRA'
        - 'CTRCM'
        - 'CTRF'
        - 'CTRM'
        - 'CTRR'
        - 'CTRS'
        - 'CVNT'
        - 'DAM'
        - 'DAMQ'
        - 'DAMSB'
        - 'DARY'
        - 'DCKD'
        - 'DCKY'
        - 'DIKE'
        - 'DIP'
        - 'DPOF'
        - 'EST'
        - 'ESTO'
        - 'ESTR'
        - 'ESTSG'
        - 'ESTT'
        - 'ESTX'
        - 'FCL'
        - 'FNDY'
        - 'FRM'
        - 'FRMQ'
        - 'FRMS'
        - 'FRMT'
        - 'FT'
        - 'FY'
        - 'FYT'
        - 'GATE'
        - 'GDN'
        - 'GHAT'
        - 'GHSE'
        - 'GOSP'
        - 'GOVL'
        - 'GRVE'
        - 'HERM'
        - 'HLT'
        - 'HMSD'
        - 'HSE'
        - 'HSEC'
        - 'HSP'
        - 'HSPC'
        - 'HSPD'
        - 'HSPL'
        - 'HSTS'
        - 'HTL'
        - 'HUT'
        - 'HUTS'
        - 'INSM'
        - 'ITTR'
        - 'JTY'
        - 'LDNG'
        - 'LEPC'
        - 'LIBR'
        - 'LNDF'
        - 'LOCK'
        - 'LTHSE'
        - 'MALL'
        - 'MAR'
        - 'MFG'
        - 'MFGB'
        - 'MFGC'
        - 'MFGCU'
        - 'MFGLM'
        - 'MFGM'
        - 'MFGPH'
        - 'MFGQ'
        - 'MFGSG'
        - 'MKT'
        - 'ML'
        - 'MLM'
        - 'MLO'
        - 'MLSG'
        - 'MLSGQ'
        - 'MLSW'
        - 'MLWND'
        - 'MLWTR'
        - 'MN'
        - 'MNAU'
        - 'MNC'
        - 'MNCR'
        - 'MNCU'
        - 'MNFE'
        - 'MNMT'
        - 'MNN'
        - 'MNQ'
        - 'MNQR'
        - 'MOLE'
        - 'MSQE'
        - 'MSSN'
        - 'MSSNQ'
        - 'MSTY'
        - 'MTRO'
        - 'MUS'
        - 'NOV'
        - 'NSY'
        - 'OBPT'
        - 'OBS'
        - 'OBSR'
        - 'OILJ'
        - 'OILQ'
        - 'OILR'
        - 'OILT'
        - 'OILW'
        - 'OPRA'
        - 'PAL'
        - 'PGDA'
        - 'PIER'
        - 'PKLT'
        - 'PMPO'
        - 'PMPW'
        - 'PO'
        - 'PP'
        - 'PPQ'
        - 'PRKGT'
        - 'PRKHQ'
        - 'PRN'
        - 'PRNJ'
        - 'PRNQ'
        - 'PS'
        - 'PSH'
        - 'PSN'
        - 'PSTB'
        - 'PSTC'
        - 'PSTP'
        - 'PYR'
        - 'PYRS'
        - 'QUAY'
        - 'RDCR'
        - 'RDIN'
        - 'RECG'
        - 'RECR'
        - 'REST'
        - 'RET'
        - 'RHSE'
        - 'RKRY'
        - 'RLG'
        - 'RLGR'
        - 'RNCH'
        - 'RSD'
        - 'RSGNL'
        - 'RSRT'
        - 'RSTN'
        - 'RSTNQ'
        - 'RSTP'
        - 'RSTPQ'
        - 'RUIN'
        - 'SCH'
        - 'SCHA'
        - 'SCHC'
        - 'SCHL'
        - 'SCHM'
        - 'SCHN'
        - 'SCHT'
        - 'SECP'
        - 'SHPF'
        - 'SHRN'
        - 'SHSE'
        - 'SLCE'
        - 'SNTR'
        - 'SPA'
        - 'SPLY'
        - 'SQR'
        - 'STBL'
        - 'STDM'
        - 'STNB'
        - 'STNC'
        - 'STNE'
        - 'STNF'
        - 'STNI'
        - 'STNM'
        - 'STNR'
        - 'STNS'
        - 'STNW'
        - 'STPS'
        - 'SWT'
        - 'SYG'
        - 'THTR'
        - 'TMB'
        - 'TMPL'
        - 'TNKD'
        - 'TOLL'
        - 'TOWR'
        - 'TRAM'
        - 'TRANT'
        - 'TRIG'
        - 'TRMO'
        - 'TWO'
        - 'UNIP'
        - 'UNIV'
        - 'USGE'
        - 'VETF'
        - 'WALL'
        - 'WALLA'
        - 'WEIR'
        - 'WHRF'
        - 'WRCK'
        - 'WTRW'
        - 'ZNF'
        - 'ZOO'
    feature_codes_t_all:
        - 'ASPH'
        - 'ATOL'
        - 'BAR'
        - 'BCH'
        - 'BCHS'
        - 'BDLD'
        - 'BLDR'
        - 'BLHL'
        - 'BLOW'
        - 'BNCH'
        - 'BUTE'
        - 'CAPE'
        - 'CFT'
        - 'CLDA'
        - 'CLF'
        - 'CNYN'
        - 'CONE'
        - 'CRDR'
        - 'CRQ'
        - 'CRQS'
        - 'CRTR'
        - 'CUET'
        - 'DLTA'
        - 'DPR'
        - 'DSRT'
        - 'DUNE'
        - 'DVD'
        - 'ERG'
        - 'FAN'
        - 'FORD'
        - 'FSR'
        - 'GAP'
        - 'GRGE'
        - 'HDLD'
        - 'HLL'
        - 'HLLS'
        - 'HMCK'
        - 'HMDA'
        - 'INTF'
        - 'ISL'
        - 'ISLET'
        - 'ISLF'
        - 'ISLM'
        - 'ISLS'
        - 'ISLT'
        - 'ISLX'
        - 'ISTH'
        - 'KRST'
        - 'LAVA'
        - 'LEV'
        - 'MESA'
        - 'MND'
        - 'MRN'
        - 'MT'
        - 'MTS'
        - 'NKM'
        - 'NTK'
        - 'NTKS'
        - 'PAN'
        - 'PANS'
        - 'PASS'
        - 'PEN'
        - 'PENX'
        - 'PK'
        - 'PKS'
        - 'PLAT'
        - 'PLATX'
        - 'PLDR'
        - 'PLN'
        - 'PLNX'
        - 'PROM'
        - 'PT'
        - 'PTS'
        - 'RDGB'
        - 'RDGE'
        - 'REG'
        - 'RK'
        - 'RKFL'
        - 'RKS'
        - 'SAND'
        - 'SBED'
        - 'SCRP'
        - 'SDL'
        - 'SHOR'
        - 'SINK'
        - 'SLID'
        - 'SLP'
        - 'SPIT'
        - 'SPUR'
        - 'TAL'
        - 'TRGD'
        - 'TRR'
        - 'UPLD'
        - 'VAL'
        - 'VALG'
        - 'VALS'
        - 'VALX'
        - 'VLC'
    feature_codes_u_all:
        - 'APNU'
        - 'ARCU'
        - 'ARRU'
        - 'BDLU'
        - 'BKSU'
        - 'BNKU'
        - 'BSNU'
        - 'CDAU'
        - 'CNSU'
        - 'CNYU'
        - 'CRSU'
        - 'DEPU'
        - 'EDGU'
        - 'ESCU'
        - 'FANU'
        - 'FLTU'
        - 'FRZU'
        - 'FURU'
        - 'GAPU'
        - 'GLYU'
        - 'HLLU'
        - 'HLSU'
        - 'HOLU'
        - 'KNLU'
        - 'KNSU'
        - 'LDGU'
        - 'LEVU'
        - 'MESU'
        - 'MNDU'
        - 'MOTU'
        - 'MTU'
        - 'PKSU'
        - 'PKU'
        - 'PLNU'
        - 'PLTU'
        - 'PNLU'
        - 'PRVU'
        - 'RDGU'
        - 'RDSU'
        - 'RFSU'
        - 'RFU'
        - 'RISU'
        - 'SCNU'
        - 'SCSU'
        - 'SDLU'
        - 'SHFU'
        - 'SHLU'
        - 'SHSU'
        - 'SHVU'
        - 'SILU'
        - 'SLPU'
        - 'SMSU'
        - 'SMU'
        - 'SPRU'
        - 'TERU'
        - 'TMSU'
        - 'TMTU'
        - 'TNGU'
        - 'TRGU'
        - 'TRNU'
        - 'VALU'
        - 'VLSU'
    feature_codes_v_all:
        - 'BUSH'
        - 'CULT'
        - 'FRST'
        - 'FRSTF'
        - 'GROVE'
        - 'GRSLD'
        - 'GRVC'
        - 'GRVO'
        - 'GRVP'
        - 'GRVPN'
        - 'HTH'
        - 'MDW'
        - 'OCH'
        - 'SCRB'
        - 'TREE'
        - 'TUND'
        - 'VIN'
        - 'VINS'

    feature_codes_p_district_places:
        - 'PPL'
        - 'PPLX'
    feature_codes_p_admin_places:
        - 'PPL'
        - 'PPLA'
        - 'PPLA2'
        - 'PPLA3'
        - 'PPLA4'
        - 'PPLA5'
        - 'PPLC'
        - 'PPLF'
        - 'PPLG'
        - 'PPLL'
        - 'PPLQ'
        - 'PPLR'
        - 'PPLS'
        - 'PPLW'
        - 'PPLX'
        - 'STLMT'
    feature_codes_p_next_location:
        - 'PPL'
        - 'PPLA'
        - 'PPLA2'
        - 'PPLA3'
        - 'PPLA4'
        - 'PPLA5'
        - 'PPLC'
        - 'PPLF'
        - 'PPLG'
        - 'PPLQ'
        - 'PPLS'
        - 'PPLW'
        - 'PPLX'
        - 'STLMT'
    feature_codes_t_hills:
        - 'HLL'
        - 'MT'
        - 'MTS'
        - 'PK'
        - 'RK'
