parameters:
    # district admin codes
    # --------------------
    # - default: a4
    # - see: LocationServiceConfig::getAdminCodesGeneral
    #
    # a1 - check a1 for district
    # a2 - check a1 and a2 for district
    # a3 - check a1, a2 and a3 for district
    # a4 - check a1, a2, a3 and a4 for district
    #
    # Germany for example, uses all 4 properties (a4).
    #
    # --------------------------------
    # To choose the best strategy,
    # use the following SQL Query
    # to count the a1 - a4 properties:
    # --------------------------------
    # SELECT
    #     MIN(country) AS country,
    #     scenario,
    #     COUNT(*) AS count
    # FROM (
    #     SELECT
    #         CASE
    #             WHEN ac.admin2_code IS NOT NULL AND ac.admin3_code IS NOT NULL AND ac.admin4_code IS NOT NULL THEN 'a4'
    #             WHEN ac.admin2_code IS NOT NULL AND ac.admin3_code IS NOT NULL AND ac.admin4_code IS NULL THEN 'a3'
    #             WHEN ac.admin2_code IS NOT NULL AND ac.admin3_code IS NULL AND ac.admin4_code IS NULL THEN 'a2'
    #             WHEN ac.admin2_code IS NULL AND ac.admin3_code IS NULL AND ac.admin4_code IS NULL THEN 'a1'
    #             ELSE 'a0'
    #         END AS scenario,
    #         c.code as country
    #     FROM
    #         location l
    #     INNER JOIN
    #         admin_code ac ON l.admin_code_id = ac.id
    #     INNER JOIN
    #         country c ON l.country_id = c.id
    #     WHERE
    #         -- country
    #         l.country_id = '74' AND
    #
    #         -- only places with feature class P
    #         l.feature_class_id = '2'
    # ) AS scenarios
    # GROUP BY
    #     scenario
    # ORDER BY
    #     scenario DESC;
    #
    # Returns for Germany:
    # --------------------
    #
    # country | scenario | count
    # --------------------------
    # DE      | a4       | 79559
    # DE      | a3       |     6
    # DE      | a2       |     1
    # DE      | a1       |   200
    # DE      | a0       |     0
    #
    # The beste strategy would be:
    # ----------------------------
    #
    # DE: '%admin_codes_a4%'
    #
    # Check the a3, a2 and a1 location to maybe do some fine-tuning.
    #
    district_match:
        AD: '%admin_codes_a1%'
        AE:	'%admin_codes_a3%'
        AF:	'%admin_codes_a2%'
        AG:	'%admin_codes_a1%'
        AI:	'%admin_codes_a1%'
        AL:	'%admin_codes_a3%'
        AM:	'%admin_codes_a1%'
        AO:	'%admin_codes_a1%'
        AQ:	'%admin_codes_a1%'
        AR:	'%admin_codes_a2%'
        AS:	'%admin_codes_a1%'
        AT:	'%admin_codes_a3%'
        AU:	'%admin_codes_a2%'
        AW:	'%admin_codes_a1%'
        AX:	'%admin_codes_a2%'
        AZ:	'%admin_codes_a1%'
        BA:	'%admin_codes_a1%'
        BB:	'%admin_codes_a1%'
        BD:	'%admin_codes_a4%'
        BE:	'%admin_codes_a4%'
        BF:	'%admin_codes_a1%' # '%admin_codes_a2%'
        BG:	'%admin_codes_a3%' # '%admin_codes_a1%', '%admin_codes_a2%'
        BH:	'%admin_codes_a1%'
        BI:	'%admin_codes_a2%'
        BJ:	'%admin_codes_a1%'
        BM:	'%admin_codes_a1%'
        BN:	'%admin_codes_a1%'
        BO:	'%admin_codes_a1%'
        BQ:	'%admin_codes_a1%'
        BR:	'%admin_codes_a2%'
        BS:	'%admin_codes_a1%'
        BT:	'%admin_codes_a1%'
        BW:	'%admin_codes_a1%'
        BY:	'%admin_codes_a1%'
        BZ:	'%admin_codes_a1%'
        CA:	'%admin_codes_a1%'
        CC:	'%admin_codes_a1%'
        CD:	'%admin_codes_a2%'
        CF:	'%admin_codes_a2%'
        CG:	'%admin_codes_a1%'
        CH:	'%admin_codes_a3%'
        CI:	'%admin_codes_a1%'
        CK:	'%admin_codes_a1%'
        CL:	'%admin_codes_a3%' # '%admin_codes_a1%'
        CM:	'%admin_codes_a1%'
        CN:	'%admin_codes_a2%'
        CO:	'%admin_codes_a2%'
        CR:	'%admin_codes_a1%' # '%admin_codes_a3%'
        CU:	'%admin_codes_a2%'
        CV:	'%admin_codes_a1%'
        CW:	'%admin_codes_a1%'
        CX:	'%admin_codes_a1%'
        CY:	'%admin_codes_a2%'
        CZ:	'%admin_codes_a3%'
        DE:	'%admin_codes_a4%'
        DJ:	'%admin_codes_a1%'
        DK:	'%admin_codes_a2%'
        DM:	'%admin_codes_a1%'
        DO:	'%admin_codes_a4%'
        DZ:	'%admin_codes_a1%'
        EC:	'%admin_codes_a3%'
        EE:	'%admin_codes_a3%'
        EG:	'%admin_codes_a1%'
        ER:	'%admin_codes_a2%'
        ES:	'%admin_codes_a3%'
        ET:	'%admin_codes_a1%'
        FI:	'%admin_codes_a3%'
        FJ:	'%admin_codes_a2%'
        FK:	'%admin_codes_a1%'
        FM:	'%admin_codes_a2%'
        FO:	'%admin_codes_a2%'
        FR:	'%admin_codes_a4%'
        GA:	'%admin_codes_a1%'
        GB:	'%admin_codes_a2%' # '%admin_codes_a4%'
        GD:	'%admin_codes_a1%'
        GE:	'%admin_codes_a1%'
        GF:	'%admin_codes_a4%'
        GH:	'%admin_codes_a2%'
        GI:	'%admin_codes_a1%'
        GL:	'%admin_codes_a1%'
        GM:	'%admin_codes_a1%'
        GN:	'%admin_codes_a2%'
        GP:	'%admin_codes_a1%'
        GQ:	'%admin_codes_a1%'
        GR:	'%admin_codes_a3%'
        GT:	'%admin_codes_a2%' # '%admin_codes_a1%'
        GU:	'%admin_codes_a1%'
        GW:	'%admin_codes_a1%'
        GY:	'%admin_codes_a1%'
        HK:	'%admin_codes_a1%'
        HN:	'%admin_codes_a1%'
        HR:	'%admin_codes_a2%' # '%admin_codes_a1%'
        HT:	'%admin_codes_a2%'
        HU:	'%admin_codes_a1%'
        ID:	'%admin_codes_a2%'
        IE:	'%admin_codes_a2%'
        IL:	'%admin_codes_a1%'
        IM:	'%admin_codes_a1%'
        IN:	'%admin_codes_a2%'
        IO:	'%admin_codes_a1%'
        IQ:	'%admin_codes_a2%'
        IR:	'%admin_codes_a1%'
        IS:	'%admin_codes_a2%'
        IT:	'%admin_codes_a3%'
        JM:	'%admin_codes_a2%'
        JO:	'%admin_codes_a1%'
        JP:	'%admin_codes_a1%' # '%admin_codes_a2%'
        KE:	'%admin_codes_a1%'
        KG:	'%admin_codes_a1%'
        KH:	'%admin_codes_a3%'
        KI:	'%admin_codes_a2%'
        KM:	'%admin_codes_a1%'
        KN:	'%admin_codes_a1%'
        KP:	'%admin_codes_a1%'
        KR:	'%admin_codes_a3%'
        KW:	'%admin_codes_a1%'
        KY:	'%admin_codes_a1%'
        KZ:	'%admin_codes_a1%'
        LA:	'%admin_codes_a1%'
        LB:	'%admin_codes_a1%'
        LC:	'%admin_codes_a1%'
        LI:	'%admin_codes_a1%'
        LK:	'%admin_codes_a4%'
        LR:	'%admin_codes_a1%'
        LS:	'%admin_codes_a1%'
        LT:	'%admin_codes_a3%'
        LU:	'%admin_codes_a2%'
        LV:	'%admin_codes_a2%'
        LY:	'%admin_codes_a1%'
        MA:	'%admin_codes_a2%'
        MC:	'%admin_codes_a1%'
        MD:	'%admin_codes_a1%'
        ME:	'%admin_codes_a1%'
        MG:	'%admin_codes_a4%'
        MH:	'%admin_codes_a1%'
        MK:	'%admin_codes_a1%'
        ML:	'%admin_codes_a1%'
        MM:	'%admin_codes_a3%'
        MN:	'%admin_codes_a1%'
        MO:	'%admin_codes_a1%'
        MP:	'%admin_codes_a1%'
        MQ:	'%admin_codes_a1%' # '%admin_codes_a4%'
        MR:	'%admin_codes_a1%'
        MS:	'%admin_codes_a1%'
        MT:	'%admin_codes_a1%'
        MU:	'%admin_codes_a1%'
        MV:	'%admin_codes_a1%'
        MW:	'%admin_codes_a2%'
        MX:	'%admin_codes_a2%'
        MY:	'%admin_codes_a2%'
        MZ:	'%admin_codes_a1%'
        NA:	'%admin_codes_a1%'
        NC:	'%admin_codes_a1%'
        NE:	'%admin_codes_a1%'
        NF:	'%admin_codes_a1%'
        NG:	'%admin_codes_a2%'
        NI:	'%admin_codes_a1%'
        NL:	'%admin_codes_a2%'
        NO:	'%admin_codes_a2%'
        NP:	'%admin_codes_a3%'
        NR:	'%admin_codes_a1%'
        NU:	'%admin_codes_a1%'
        NZ:	'%admin_codes_a2%'
        OM:	'%admin_codes_a1%'
        PA:	'%admin_codes_a3%'
        PE:	'%admin_codes_a3%'
        PF:	'%admin_codes_a1%'
        PG:	'%admin_codes_a1%'
        PH:	'%admin_codes_a3%'
        PK:	'%admin_codes_a2%'
        PL:	'%admin_codes_a3%'
        PM:	'%admin_codes_a1%'
        PR:	'%admin_codes_a2%'
        PS:	'%admin_codes_a1%'
        PT:	'%admin_codes_a3%'
        PW:	'%admin_codes_a1%'
        PY:	'%admin_codes_a2%'
        QA:	'%admin_codes_a1%'
        RE:	'%admin_codes_a1%' # '%admin_codes_a4%'
        RO:	'%admin_codes_a2%'
        RS:	'%admin_codes_a3%'
        RU:	'%admin_codes_a1%'
        RW:	'%admin_codes_a4%'
        SA:	'%admin_codes_a1%'
        SB:	'%admin_codes_a1%'
        SC:	'%admin_codes_a1%'
        SD:	'%admin_codes_a1%'
        SE:	'%admin_codes_a2%'
        SG:	'%admin_codes_a1%'
        SH:	'%admin_codes_a1%'
        SI:	'%admin_codes_a1%'
        SK:	'%admin_codes_a3%'
        SL:	'%admin_codes_a1%'
        SM:	'%admin_codes_a1%'
        SN:	'%admin_codes_a1%'
        SO:	'%admin_codes_a1%'
        SR:	'%admin_codes_a1%'
        SS:	'%admin_codes_a1%'
        ST:	'%admin_codes_a1%'
        SV:	'%admin_codes_a1%'
        SX:	'%admin_codes_a1%'
        SY:	'%admin_codes_a1%'
        SZ:	'%admin_codes_a1%'
        TC:	'%admin_codes_a1%'
        TD:	'%admin_codes_a1%'
        TG:	'%admin_codes_a1%'
        TH:	'%admin_codes_a3%'
        TJ:	'%admin_codes_a1%'
        TK:	'%admin_codes_a1%'
        TL:	'%admin_codes_a3%'
        TM:	'%admin_codes_a1%'
        TN:	'%admin_codes_a3%' # '%admin_codes_a1%'
        TO:	'%admin_codes_a1%'
        TR:	'%admin_codes_a1%'
        TT:	'%admin_codes_a1%'
        TV:	'%admin_codes_a1%'
        TW:	'%admin_codes_a4%'
        TZ:	'%admin_codes_a3%'
        UA:	'%admin_codes_a2%'
        UG:	'%admin_codes_a4%' # '%admin_codes_a2%'
        UM:	'%admin_codes_a1%'
        US:	'%admin_codes_a2%'
        UY:	'%admin_codes_a1%' # '%admin_codes_a2%'
        UZ:	'%admin_codes_a1%'
        VA:	'%admin_codes_a1%'
        VC:	'%admin_codes_a1%'
        VE:	'%admin_codes_a2%'
        VG:	'%admin_codes_a1%'
        VI:	'%admin_codes_a2%'
        VN:	'%admin_codes_a2%'
        VU:	'%admin_codes_a1%'
        WF:	'%admin_codes_a1%' # '%admin_codes_a2%'
        WS:	'%admin_codes_a1%'
        XK:	'%admin_codes_a2%'
        YE:	'%admin_codes_a1%' # '%admin_codes_a1%'
        YT:	'%admin_codes_a1%'
        ZA:	'%admin_codes_a3%'
        ZM:	'%admin_codes_a1%'
        ZW:	'%admin_codes_a1%'
        # Old configuration
        # AT: '%admin_codes_a3%'
        # CH: '%admin_codes_a3%'
        # CN: '%admin_codes_a2%'
        # CZ: '%admin_codes_a1%'
        # DK: '%admin_codes_a2%'
        # EE: '%admin_codes_a3%'
        # ES: '%admin_codes_a3%'
        # GB: '%admin_codes_a2%'
        # JP: '%admin_codes_a1%'
        # MT: '%admin_codes_a1%'
        # NL: '%admin_codes_a2%'
        # PL: '%admin_codes_a3%'
        # PT: '%admin_codes_a2%'
        # SE: '%admin_codes_a2%'
        # US: '%admin_codes_a2%'

    # some borough filters
    filter_new_york_city:
        a1: 'NY'
        a2: '047|061'

    # location configuration
    location_configuration:
        default:
            location_reference:
                feature_class: '%feature_class_p%'
                feature_codes: '%feature_codes_p_next_location%'
            district:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                sort_by_population: false
                admin_codes: null
                with_population: null
            borough:
                visible: false
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPLC'
                    - 'PPL'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                sort_by_population: false
                admin_codes: null
                with_population: true
            state:
                feature_class: '%feature_class_a%'
                feature_codes:
                    - 'ADM1'
                sort_by_feature_codes: true
                sort_by_population: false
                admin_codes:
                    a1: '%db_from_location%'
                with_population: null
                use_coordinate: false
        DE:
            district: null
            borough: null
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLC'
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPL'
                    - 'PPLA'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: false
                sort_by_population: true
                admin_codes: null
                with_population: true
        GB:
            district:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                sort_by_population: false
                admin_codes: null
                with_population: null
                exceptions:
                    - filter:
                          a2: 'GLA'
                      feature_codes:
                        - 'PPLA3'
                      sort_by_feature_codes: true
                      sort_by_population: false
            borough: null
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLC'
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPL'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                sort_by_population: false
                admin_codes: null
                with_population: true
        MT:
            district:
                visible: false
            borough: null
            city: null
            state:
                feature_class: '%feature_class_a%'
                feature_codes:
                    - 'ADMD'
                sort_by_feature_codes: true
                sort_by_population: false
                admin_codes:
                    a1: '00'
                with_population: null
                use_coordinate: true
        US:
            district:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                sort_by_population: false
                admin_codes: null
                with_population: null
                must_match_admin_codes: true
                exceptions:
                    - filter: '%filter_new_york_city%'
                      feature_codes:
                          - 'PPLX'
                      sort_by_feature_codes: true
                      sort_by_population: false
                      admin_codes:
                          a1: 'NY'
                          a2: '%db_from_location%'
            borough:
                visible: false
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                sort_by_population: false
                admin_codes: null
                with_population: null
                exceptions:
                    -   filter: '%filter_new_york_city%'
                        visible: true
                        feature_codes:
                            - 'PPLA2'
                        sort_by_feature_codes: true
                        sort_by_population: false
                        admin_codes:
                            a1: 'NY'
                            a2: '%db_from_location%'
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    #- 'PPLA5'
                    #- 'PPLA4'
                    #- 'PPLA3'
                    - 'PPLC'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPL'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                sort_by_population: false
                admin_codes: null
                with_population: true
                #must_match_admin_codes: true
                exceptions:
                    - filter: '%filter_new_york_city%'
                      feature_codes:
                          - 'PPL'
                      sort_by_feature_codes: true
                      sort_by_population: false
                      admin_codes:
                          a1: 'NY'
                          a2: 'null'
