parameters:
    # district admin codes
    district_match:
        AT: '%admin_codes_a3%'
        CH: '%admin_codes_a3%'
        CZ: '%admin_codes_a1%'
        DK: '%admin_codes_a2%'
        EE: '%admin_codes_a3%'
        ES: '%admin_codes_a3%'
        GB: '%admin_codes_a2%'
        JP: '%admin_codes_a1%'
        MT: '%admin_codes_a1%'
        NL: '%admin_codes_a2%'
        PL: '%admin_codes_a3%'
        PT: '%admin_codes_a2%'
        SE: '%admin_codes_a2%'
        US: '%admin_codes_a2%'

    # some borough filters
    filter_new_york_city:
        a1: 'NY'
        a2: '047|061'

    # location configuration
    location_configuration:
        default:
            location_reference:
                feature_class: '%feature_class_p%'
                feature_codes: '%feature_codes_p_next_location%'
            district:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                sort_by_population: false
                admin_codes: null
                with_population: null
            borough:
                visible: false
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPLC'
                    - 'PPL'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                sort_by_population: false
                admin_codes: null
                with_population: true
            state:
                feature_class: '%feature_class_a%'
                feature_codes:
                    - 'ADM1'
                sort_by_feature_codes: true
                sort_by_population: false
                admin_codes:
                    a1: '%db_from_location%'
                with_population: null
                use_coordinate: false
        DE:
            district: null
            borough: null
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLC'
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPL'
                    - 'PPLA'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: false
                sort_by_population: true
                admin_codes: null
                with_population: true
        GB:
            district:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                sort_by_population: false
                admin_codes: null
                with_population: null
                exceptions:
                    - filter:
                          a2: 'GLA'
                      feature_codes:
                        - 'PPLA3'
                      sort_by_feature_codes: true
                      sort_by_population: false
            borough: null
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLC'
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPL'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                sort_by_population: false
                admin_codes: null
                with_population: true
        MT:
            district:
                visible: false
            borough: null
            city: null
            state:
                feature_class: '%feature_class_a%'
                feature_codes:
                    - 'ADMD'
                sort_by_feature_codes: true
                sort_by_population: false
                admin_codes:
                    a1: '00'
                with_population: null
                use_coordinate: true
        US:
            district:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                sort_by_population: false
                admin_codes: null
                with_population: null
                must_match_admin_codes: true
                exceptions:
                    - filter: '%filter_new_york_city%'
                      feature_codes:
                          - 'PPLX'
                      sort_by_feature_codes: true
                      sort_by_population: false
                      admin_codes:
                          a1: 'NY'
                          a2: '%db_from_location%'
            borough:
                visible: false
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                sort_by_population: false
                admin_codes: null
                with_population: null
                exceptions:
                    -   filter: '%filter_new_york_city%'
                        visible: true
                        feature_codes:
                            - 'PPLA2'
                        sort_by_feature_codes: true
                        sort_by_population: false
                        admin_codes:
                            a1: 'NY'
                            a2: '%db_from_location%'
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    #- 'PPLA5'
                    #- 'PPLA4'
                    #- 'PPLA3'
                    - 'PPLC'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPL'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                sort_by_population: false
                admin_codes: null
                with_population: true
                #must_match_admin_codes: true
                exceptions:
                    - filter: '%filter_new_york_city%'
                      feature_codes:
                          - 'PPL'
                      sort_by_feature_codes: true
                      sort_by_population: false
                      admin_codes:
                          a1: 'NY'
                          a2: 'null'
