parameters:
    feature_class_a: 'A'
    feature_class_p: 'P'

    feature_codes_p_all:
        - 'PPL'
        - 'PPLA'
        - 'PPLA2'
        - 'PPLA3'
        - 'PPLA4'
        - 'PPLA5'
        - 'PPLC'
        - 'PPLF'
        - 'PPLG'
        - 'PPLQ'
        - 'PPLR'
        - 'PPLS'
        - 'PPLW'
        - 'PPLX'
        - 'STLMT'

    admin_codes_a0: 'a0'
    admin_codes_a1: 'a1'
    admin_codes_a2: 'a2'
    admin_codes_a3: 'a3'
    admin_codes_a4: 'a4'

    admin_codes_all:
        - '%admin_codes_a1%'
        - '%admin_codes_a2%'
        - '%admin_codes_a3%'
        - '%admin_codes_a4%'

    district_match:
        AT: '%admin_codes_a3%'
        CH: '%admin_codes_a3%'
        CZ: '%admin_codes_a1%'
        DK: '%admin_codes_a2%'
        EE: '%admin_codes_a3%'
        ES: '%admin_codes_a3%'
        GB: '%admin_codes_a2%'
        JP: '%admin_codes_a1%'
        MT: '%admin_codes_a1%'
        NL: '%admin_codes_a2%'
        PL: '%admin_codes_a3%'
        PT: '%admin_codes_a2%'
        SE: '%admin_codes_a2%'
        US: '%admin_codes_a2%'

    # some db configuration names
    db_not_null: 'not-null'
    db_null: 'null'
    db_from_location: 'from-location'

    # Some borough filters
    filter_new_york_city:
        a1: 'NY'
        a2: '047|061'

    location_country:
        default:
            location_reference:
                feature_class: '%feature_class_p%'
                feature_codes: '%feature_codes_p_all%'
            district:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                admin_codes: null
                with_population: null
            borough:
                visible: false
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPLC'
                    - 'PPL'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                admin_codes: null
                with_population: true
            state:
                feature_class: '%feature_class_a%'
                feature_codes:
                    - 'ADM1'
                sort_by_feature_codes: true
                admin_codes:
                    a1: '%db_from_location%'
                with_population: null
                use_coordinate: false
        DE:
            district: null
            borough: null
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLC'
                    - 'PPL'
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                admin_codes: null
                with_population: true
        GB:
            district:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                admin_codes: null
                with_population: null
                exceptions:
                    - filter:
                          a2: 'GLA'
                      feature_codes:
                        - 'PPLA3'
                      sort_by_feature_codes: true
            borough: null
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLC'
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPL'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                admin_codes: null
                with_population: true
        MT:
            district:
                visible: false
            borough: null
            city: null
            state:
                feature_class: '%feature_class_a%'
                feature_codes:
                    - 'ADMD'
                sort_by_feature_codes: true
                admin_codes:
                    a1: '00'
                with_population: null
                use_coordinate: true
        US:
            district:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                admin_codes: null
                with_population: null
                must_match_admin_codes: true
                exceptions:
                    - filter: '%filter_new_york_city%'
                      feature_codes:
                          - 'PPLX'
                      sort_by_feature_codes: true
                      admin_codes:
                          a1: 'NY'
                          a2: '%db_from_location%'
            borough:
                visible: false
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                admin_codes: null
                with_population: null
                exceptions:
                    -   filter: '%filter_new_york_city%'
                        visible: true
                        feature_codes:
                            - 'PPLA2'
                        sort_by_feature_codes: true
                        admin_codes:
                            a1: 'NY'
                            a2: '%db_from_location%'
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    #- 'PPLA5'
                    #- 'PPLA4'
                    #- 'PPLA3'
                    - 'PPLC'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPL'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                admin_codes: null
                with_population: true
                #must_match_admin_codes: true
                exceptions:
                    - filter: '%filter_new_york_city%'
                      feature_codes:
                          - 'PPL'
                      sort_by_feature_codes: true
                      admin_codes:
                          a1: 'NY'
                          a2: 'null'
