parameters:
    feature_class_a: 'A'
    feature_class_p: 'P'

    admin_codes_a1: 'a1'
    admin_codes_a2: 'a2'
    admin_codes_a3: 'a3'
    admin_codes_a4: 'a4'

    admin_codes_all:
        - '%admin_codes_a1%'
        - '%admin_codes_a2%'
        - '%admin_codes_a3%'
        - '%admin_codes_a4%'

    district_match:
        US: '%admin_codes_a1%'
        JP: '%admin_codes_a1%'
        CZ: '%admin_codes_a1%'
        DK: '%admin_codes_a2%'
        GB: '%admin_codes_a2%'
        NL: '%admin_codes_a2%'
        PT: '%admin_codes_a2%'
        SE: '%admin_codes_a2%'
        AT: '%admin_codes_a3%'
        CH: '%admin_codes_a3%'
        EE: '%admin_codes_a3%'
        ES: '%admin_codes_a3%'
        PL: '%admin_codes_a3%'

    db_not_null: 'not-null'
    db_null: 'null'

    location_country:
        default:
            district:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                admin_codes: null
                with_population: null
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPLC'
                    - 'PPL'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                admin_codes: null
                with_population: true
        DE:
            district: null
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLC'
                    - 'PPL'
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                admin_codes: null
                with_population: true
        GB:
            district:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                sort_by_feature_codes: false
                admin_codes: null
                with_population: null
                exceptions:
                    - admin_codes:
                          a2: 'GLA'
                      feature_codes:
                        - 'PPLA3'
                      sort_by_feature_codes: true
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLC'
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPL'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                admin_codes: null
                with_population: true
        US:
            district:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLX'
                    - 'PPL'
                    - 'PPLW'
                    - 'PPLA2'
                sort_by_feature_codes: false
                admin_codes:
                    a2: 'not-null'
                with_population: null
            city:
                feature_class: '%feature_class_p%'
                feature_codes:
                    - 'PPLA5'
                    - 'PPLA4'
                    - 'PPLA3'
                    - 'PPLA2'
                    - 'PPLA'
                    - 'PPLC'
                    - 'PPL'
                    - 'PPLF'
                    - 'PPLG'
                    - 'PPLQ'
                    - 'PPLR'
                    - 'PPLS'
                    - 'PPLW'
                    - 'STLMT'
                sort_by_feature_codes: true
                admin_codes:
                    a2: 'null'
                with_population: true
