parameters:
    # next places configuration
    next_places:
        limit:
            default: 1
            feature_class:
                A: 10
                H: 10
                L: 10
                P: 10
                R: 10
                S: 10
                T: 15
                U: 10
                V: 10
            feature_code:
                S.AIRP: 10 # Airports
            overwrites:
                DE:
                    default: 1
                    feature_class:
                        A: 10
                        H: 10
                        L: 10
                        P: 10
                        R: 10
                        S: 10
                        T: 15
                        U: 10
                        V: 10
                    feature_code:
                        S.AIRP: 10 # Airports

        distance:
            default: 1000
            feature_class:
                A: 10000
                H: 10000
                L: 10000
                P: 10000
                R: 10000
                S: 10000
                T: 20000
                U: 10000
                V: 15000
            feature_code:
                S.AIRP: 200000 # Airports
            overwrites:
                DE:
                    default: 1000
                    feature_class:
                        A: 10000
                        H: 10000
                        L: 10000
                        P: 10000
                        R: 10000
                        S: 10000
                        T: 20000
                        U: 10000
                        V: 15000
                    feature_code:
                        S.AIRP: 200000 # Airports

        use_admin_codes_general:
            default: false
            feature_class:
                A: true
                P: true
        use_location_country:
            default: false
            feature_class:
                A: true
                P: true

    next_places_groups:
        default:
            distance: 100000 # Within a radius of 100 kilometers (100.000 meters)
            limit:    10     # Max. 10 results per request
        next:
            cities:
                name: cities
                feature_codes:
                    - PPLA
                    - PPLA2
                    - PPLA3
            parks:
                name: parks
                feature_codes:
                    - PRK
            airports:
                name: airports
                feature_codes:
                    - AIRP
                distance: 200000
            stations:
                name: stations
                feature_codes:
                    - BUSTN
                    - BUSTP
                    - MTRO
                    - RSTN
                    - RSTP
                distance: 20000
            cinemas:
                name: cinemas
                feature_codes:
                    - THTR
            beaches:
                name: beaches
                feature_codes:
                    - BCH
                    - BCHS
                    - RDGB
                    - SHOR
            churches:
                name: churches
                feature_codes:
                    - CH
            waters:
                name: lakes, rivers
                feature_codes:
                    - LK
                    - LKS
                    - STM
            hotels:
                name: hotels
                feature_codes:
                    - HTL
            hospitals:
                name: hospitals
                feature_codes:
                    - HSP
                distance: 50000
            mountains:
                name: mountains, hills
                feature_codes:
                    - HLL
                    - MT
                    - PK
                distance: 10000
        overwrites:
            US:
                default:
                    distance: 100000 # Within a radius of 100 kilometers (100.000 meters)
                    limit: 10        # Max. 10 results per request
                next:
                    cities:
                        feature_codes:
                            - PPLA
                            - PPLA2
                            - PPLA3
                            - PPLA4
