parameters:
    # next places configuration
    next_places:
        limit:
            default: 1
            feature_class:
                A: 10
                H: 10
                L: 10
                P: 10
                R: 10
                S: 10
                T: 10
                U: 10
                V: 10
            feature_code:
                S.AIRP: 3 # Airports
        distance:
            default: null
            feature_class:
                A: 10000
                H: 10000
                L: 10000
                P: 10000
                R: 10000
                S: 10000
                T: 10000
                U: 10000
                V: 15000
            feature_code:
                S.AIRP: 200000 # Airports
        use_admin_codes_general:
            default: false
            feature_class:
                A: true
                P: true
        use_location_country:
            default: false
            feature_class:
                A: true
                P: true
